#!/usr/bin/env python3
"""Render one standalone page per piece → repo-root pieces/<id>.html.

Each page = the piece's plate or film + the full copy (src/pieces/<id>.html fragment),
with the site's CSS inlined (works from file:// and from Vercel, no build step on the page).
Re-runs are idempotent: rendering the same pieces.json + fragments yields identical bytes.
"""
import json, os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PIECES_JSON = os.path.join(ROOT, 'src', 'data', 'pieces.json')
FRAG_DIR = os.path.join(ROOT, 'src', 'pieces')
OUT_DIR = os.path.join(ROOT, 'pieces')
SRC_HTML = os.path.join(ROOT, 'src', 'index.html')

CHAPTERS = {
    '#ch1': 'The brief before the brief',
    '#ch2': 'The first build',
    '#ch3': 'The Surf Excel work',
    '#ch4': 'The GoBoult rebrand',
    '#ch5': 'The pitch, defended',
    '#ch6': 'The calendar',
    '#ch7': 'The creator scripts',
    '#ch8': 'The desk',
    '#ch9': 'The red pen',
    '#side': 'The side quests',
}

PIECE_CSS = """
  /* piece pages (generated by tools/gen_pieces.py) */
  .piecebar{position:sticky;top:0;z-index:5;display:flex;justify-content:space-between;gap:1rem;padding:.95rem 1.4rem;border-bottom:1px solid var(--line);background:rgba(0,0,0,.86);backdrop-filter:blur(8px);font-size:.7rem;letter-spacing:.08em;text-transform:uppercase}
  .piecebar a{color:var(--fg);text-decoration:none}
  .piece{max-width:46rem;margin:0 auto;padding:4.5rem 1.4rem 6rem}
  .piece .kicker{margin:0 0 1rem}
  .piece__title{font-family:var(--font-serif);font-weight:500;font-size:clamp(2.4rem,5.2vw,3.6rem);line-height:1.04;letter-spacing:-.02em;margin:0 0 2.2rem;max-width:22ch}
  .piece__art{margin:0 0 2.8rem}
  .piece__art img,.piece__art video{display:block;width:100%;height:auto;border-radius:3px;background:var(--graphite)}
  .piece__art--tall{max-width:24rem}
  .piece__art--wide{max-width:52rem}
  .piece__copy{font-size:1.05rem;line-height:1.7}
  .piece__copy p{margin:0 0 1.1em}
  .piece__copy p:last-child{margin-bottom:0}
  .piece__copy h3{font-family:var(--font-serif);font-weight:500;font-size:1.6rem;letter-spacing:-.01em;margin:2.6rem 0 .9rem}
  .piece__copy .line{font-family:var(--font-serif);font-weight:500;font-size:clamp(1.9rem,4vw,2.7rem);line-height:1.15;letter-spacing:-.015em;margin:0 0 1.5rem}
  .piece__copy blockquote{margin:1.5rem 0;padding-left:1.15rem;border-left:2px solid var(--red);font-family:var(--font-serif);font-size:1.28rem;line-height:1.45}
  .piece__copy .items{list-style:none;margin:1.5rem 0 0;padding:0}
  .piece__copy .items li{display:grid;grid-template-columns:minmax(9rem,15rem) 1fr;gap:.15rem 1.4rem;padding:.95rem 0;border-bottom:1px solid var(--line)}
  .piece__copy .items li:first-child{border-top:1px solid var(--line)}
  .piece__copy .items span{color:var(--muted)}
  .piece__copy .note,.piece__copy .mono-note{font-family:var(--font-mono);font-size:.75rem;letter-spacing:.06em;text-transform:uppercase;color:var(--muted)}
  .piece__foot{margin-top:4.5rem;padding-top:1.4rem;border-top:1px solid var(--line);display:flex;justify-content:space-between;flex-wrap:wrap;gap:.8rem;font-family:var(--font-mono);font-size:.72rem;letter-spacing:.07em;text-transform:uppercase}
  .piece__foot a{color:var(--fg);text-decoration:none}
  .piece__foot a:hover{color:var(--red)}
  @media (max-width:600px){.piece__copy .items li{grid-template-columns:1fr}}
"""


def load_pieces():
    with open(PIECES_JSON, encoding='utf8') as f:
        return json.load(f)['pieces']


def site_css():
    css = ''
    for fn in sorted(os.listdir(os.path.join(ROOT, 'src', 'css'))):
        if fn.endswith('.css'):
            with open(os.path.join(ROOT, 'src', 'css', fn), encoding='utf8') as f:
                css += f.read() + '\n'
    # css files live in src/css/ and address assets as ../../assets/ — pages live in pieces/
    css = css.replace('../../assets/', '../assets/')
    return css


def favicon():
    try:
        with open(SRC_HTML, encoding='utf8') as f:
            m = re.search(r'<link rel="icon"[^>]*>', f.read())
            if m:
                return m.group(0)
    except OSError:
        pass
    return '<link rel="icon" href="data:,">'


def title_of(p):
    t = p.get('title')
    if t:
        return t
    cap = p['cap']
    return cap.split(' \u2014 ')[0].strip() or cap


def render_figure(p):
    if p['kind'] == 'film':
        vid = (f'<video class="piece__media" controls playsinline preload="metadata" '
               f'width="432" height="768" poster="../{p["poster"]}" aria-label="{p.get("aria", "")}">'
               f'<source src="../{p["src"]}" type="video/mp4"></video>')
        return vid
    cls = 'piece__art--tall' if p.get('h', 0) > p.get('w', 0) else 'piece__art--wide'
    return (f'<img src="../{p["src"]}" alt="{p.get("alt", "")}" width="{p["w"]}" '
            f'height="{p["h"]}" class="{cls}">')


def render(p, css, favicon_tag):
    frag_path = os.path.join(FRAG_DIR, p['id'] + '.html')
    with open(frag_path, encoding='utf8') as f:
        fragment = f.read().strip()
    chapter = CHAPTERS.get(p.get('href', ''), 'The work')
    title = title_of(p)
    cap = p['cap'].replace('"', '&quot;')
    return f'''<!doctype html>
<html lang="en" class="no-js" data-theme="ink">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="{cap}">
<meta name="theme-color" content="#000000">
<title>{title} \u2014 Abhijeet Kanase</title>
{favicon_tag}
<style>
{css}{PIECE_CSS}</style>
</head>
<body>
<header class="piecebar mono">
  <a href="../index.html">&larr; The orbit</a>
  <span>Abhijeet Kanase &middot; copywriter &middot; Mumbai</span>
</header>
<main class="piece">
  <p class="kicker mono">{p['k']}</p>
  <h1 class="piece__title">{title}</h1>
  <div class="piece__art">{render_figure(p)}</div>
  <div class="piece__copy">
{fragment}
  </div>
  <footer class="piece__foot">
    <a href="../index.html{p['href']}">{chapter} &darr;</a>
    <a href="mailto:abhi.insider@gmail.com">abhi.insider@gmail.com</a>
  </footer>
</main>
</body>
</html>
'''


def generate():
    pieces = load_pieces()
    css = site_css()
    fav = favicon()
    os.makedirs(OUT_DIR, exist_ok=True)
    n, missing = 0, []
    for p in pieces:
        frag = os.path.join(FRAG_DIR, p['id'] + '.html')
        if not os.path.exists(frag):
            missing.append(p['id'])
            continue
        out = os.path.join(OUT_DIR, p['id'] + '.html')
        page = render(p, css, fav)
        with open(out, 'w', encoding='utf8') as f:
            f.write(page)
        n += 1
    print(f'  pieces: {n} pages written' + (f' ({len(missing)} without fragment: {", ".join(missing)})' if missing else ''))
    return n, missing


def check():
    pieces = load_pieces()
    css = site_css()
    fav = favicon()
    drift = []
    for p in pieces:
        frag = os.path.join(FRAG_DIR, p['id'] + '.html')
        if not os.path.exists(frag):
            continue
        out = os.path.join(OUT_DIR, p['id'] + '.html')
        if not os.path.exists(out) or open(out, encoding='utf8').read() != render(p, css, fav):
            drift.append(p['id'])
    print(f'  piece pages: in sync' if not drift else f'  piece pages: DRIFT ({", ".join(drift)})')
    return not drift


if __name__ == '__main__':
    args = sys.argv[1:]
    if '--check' in args:
        sys.exit(0 if check() else 1)
    generate()
